---

- hosts: all
  become: true
  tasks:

  - name: install apache/httpd package
    yum:
      name: httpd
      state: absent
  - name: add tree command 
    yum:
      name: tree
      state: absent
